plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Max: 125

Metrics/ParameterLists:
  Exclude:
    - lib/resteze/errors.rb

Metrics/AbcSize:
  Exclude:
    - lib/resteze/response.rb

Metrics/BlockLength:
  Exclude:
    - lib/resteze.rb
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - lib/resteze/client.rb
    - test/**/*

Metrics/MethodLength:
  Max: 15

Minitest/MultipleAssertions:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/*"
