require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

inherit_from: ../../.rubocop-shared.yml

inherit_mode:
  merge:
    - Exclude

Metrics/ParameterLists:
  Exclude:
    - lib/resty/errors.rb

Metrics/AbcSize:
  Exclude:
    - lib/resty/response.rb

Metrics/BlockLength:
  Exclude:
    - lib/resty.rb
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - lib/resty/client.rb
    - test/**/*

Minitest/MultipleAssertions:
  Max: 6

AllCops:
  Exclude:
    - 'bin/*'
