plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

Metrics/ParameterLists:
  Exclude:
    - lib/resteze/errors.rb

Metrics/AbcSize:
  Exclude:
    - lib/resteze/response.rb

Metrics/BlockLength:
  Exclude:
    - lib/resteze.rb
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - lib/resteze/client.rb
    - test/**/*

Minitest/MultipleAssertions:
  Max: 6

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
