name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.2.1"
          - "3.3"
          - "3.3.1"
          - "3.4"
          - "3.4.2"
          - "3.4.4"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests with coverage
        run: bundle exec rake test
      - name: Coveralls
        if: matrix.ruby == '3.4.4'
        uses: coverallsapp/github-action@v2

  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.2.1"
          - "3.3"
          - "3.3.1"
          - "3.4"
          - "3.4.2"
          - "3.4.4"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop
